import { DefaultLayout } from "@/layout";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout>
        <main>
          <h1 className="title">Welcome to Next.js!</h1>
          <p className="description">
            Get started by editing <code>pages/index.tsx</code>
          </p>
        </main>
      </DefaultLayout>
    </>
  );
}
